# Generated by Django 3.2 on 2021-04-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20150601_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='fulfilled_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Fulfilled on'),
        ),
    ]
