# Generated by Django 3.2 on 2021-04-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_fulfilled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='fulfilled_on',
            field=models.DateTimeField(verbose_name='Fulfilled on'),
        ),
    ]
